### ISSUE TITLE
Define and implement the initial data structures of Arlin v1

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#10]
- Kind: Statement of Work
- Title: Describe the initial data structures
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-03-19
- Version: 0.1
# SOW
## Overview

Clearly define and implement the initial data structures that will be used by the app and stored in the database.
## Tasks
- [x] Research and understand how to decide how to manage various document data in forum-like application.
- [x] Define the data collection here.
- [x] Create Users collection spec.
- [x] Create Questions collection spec.
- [x] Create Answers collection spec.
## Deliverables
- [x] Have a short data structure/schema documentation.
## Dependencies

Based on the basic features described here at https://github.com/gunadarma-academy/asde-michi/issues/9.
## Assumptions

These definitions are still very basic assumptions.

**Comment by mhaidarhanif** [comment]
## Initial structure for Users, Questions, and Answers

[OBSOLETE, do not refer]

```
+ Users
  + _id: UUID
  + createdDate: Date
  + updatedDate: Date
  + username: String

+ Questions
  + _id: UUID
  + createdDate: Date
  + updatedDate: Date
  + createdBy: Users._id
  + title: String
  + content: String

+ Answers
  + _id: UUID
  + answerTo: Quetions._id
  + createdDate: Date
  + updatedDate: Date
  + createdBy: Users._id
  + content: String
```

**Notes:**
We're not using `timestamp` type because it's only for internal use of the database, not for application.

**Comment by mhaidarhanif** [comment]
@muhpatr @ekkyvalent 

We should research and understand how to decide how to manage various document data in forum-like application. This also will affect our app's User Interface, Interaction, and Experience.

Let's rediscover the experience of Haaash and StackOverflow.
