### ISSUE TITLE
Explain the must have features of Arlin v1

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#11]
- Kind: Product Definition
- Title: Explain the must have features of Arlin v1
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-03-19
- Version: 0.1
# Product Definition
## Overview

Define the must-have features in the Minimum Viable Product (MVP) of Arlin v1.
## Tasks
- [x] Define in details what's the must-have features of Arlin in Product Documentation.
- [x] Explain about accepting an answer.
- [ ] Explain about upvoting a question by the voting system.
- [x] Explain about upvoting an answer by the voting system.
## Dependencies

Finish the initial data structure (https://github.com/gunadarma-academy/asde-michi/issues/10) first.
## Assumptions

Should only modify Questions document.

**Comment by mhaidarhanif** [comment]
**[STASHED]**
- [ ] Implement upvote in the voting system.
- [ ] User who's not the question's owner could upvote a question.
