### ISSUE TITLE
Design initial static website pages

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi#15]
- Kind: Statement of Work
- Title: Design initial static website pages
- Author: Ekky Pramana
- Affiliation: Michi
- Date: 2016-03-20
- Version: 0.1
# SOW
## Overview

To get a better understanding of the whole UI and UX design of Alin's website, I need to design the site's pages corresponded with the wire frame and color palette discussed in Issue [#6](https://github.com/gunadarma-academy/asde-michi/issues/6) and [#7](https://github.com/gunadarma-academy/asde-michi/issues/7).
## Tasks
- [x] Understanding and getting the wireframe.
- [x] Create the initial HTML body, require chosen framework.
- [x] Experiment with the CSS corresponds with the chosen palette.
- [x] Add simple interactivity/animation with CSS or JS if needed.
## Deliverables

The landing page body will be finished within 3-5 days
## Dependencies

Issue [#6](https://github.com/gunadarma-academy/asde-michi/issues/6) and [#7](https://github.com/gunadarma-academy/asde-michi/issues/7).

**Comment by mhaidarhanif** [comment]
@ekkyvalent 
Popular frontend design framework options:
- http://getbootstrap.com
- http://foundation.zurb.com
- http://semantic-ui.com
- http://purecss.io

**Comment by mhaidarhanif** [comment]
@ekkyvalent: Having some achievement or difficulty? Share your experience here.

**Comment by mhaidarhanif** [comment]
@ekkyvalent: I've pushed a medium update.
See release v0.2.1: https://github.com/gunadarma-academy/asde-michi-web/tree/v0.2.1

**Comment by mhaidarhanif** [comment]
DOM & style references:
http://semantic-ui.com/examples/homepage.html
http://tcvalentine.com/semantic-themes/minimal-slide/index.html
