### ISSUE TITLE
Specify team member roles

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#16]
- Kind: Statement of Work
- Title: Specify team member roles
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-03-20
- Version: 0.1
# SOW
## Overview

Each team members should be specified by their main tasks/works.
## Tasks
- [x] Put the main team member roles column in Team Member section of `README`.
- [x] Clearly write each member roles.
- [x] Explain again about light/rapid Holacracy.
## Deliverables

We can see explicitly who and what are the team member roles. Also understand about our management-less approach.
## Dependencies

PM and SDLC process are understandable in https://github.com/gunadarma-academy/asde-michi/issues/2 and https://github.com/gunadarma-academy/asde-michi/issues/13.
## Assumptions

The essentials of our team work are this.
