### ISSUE TITLE
Tidy up various submodules

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#21]
- Kind: Statement of Work
- Title: Tidy up various submodules
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-03-22
- Version: 0.1
# SOW
## Overview

Tidy up various submodules that include the slide, app, and the web. Because we're now have several repos:
- https://github.com/gunadarma-academy/asde-michi
- https://github.com/gunadarma-academy/asde-michi-app
- https://github.com/gunadarma-academy/asde-michi-web
- https://github.com/gunadarma-academy/asde-michi-slide
## Tasks
- [x] Migrate all external dependencies into submodules.
- [x] Make sure all submodules are linked/registered properly.
- [x] Document the way of using submodules in `README`.
  - Recommend to clone with `git clone --recursive`
  - `git submodule init`
  - `git submodule update --recursive`
## Deliverables

Everyone can understand and use submodules to pull various resources outside this repo.
