### ISSUE TITLE
Explain the specifications of Arlin logo

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#25]
- Kind: Statement of Work
- Title: Explain the specifications of Arlin logo
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-03-23
- Version: 0.3
# SOW
## Overview

Define the logo specifications and explain the meaning from its shape and color 
## Tasks
- [x] Define the logo specifications in Logo Design Specifications 
- [x] Explain the logo
- [x] List the hex color of Arlin logo  
- [x] Separate the logo into 3 types: The combined symbol and text version, text version, and symbol version 
## Deliverables

Tomorrow will be done.
## Dependencies

Finish the Logo task (https://github.com/gunadarma-academy/asde-michi/issues/7) first.

**Comment by mhaidarhanif** [comment]
@rutheodora: Check out this very short branding page https://getgrav.org/media

**Comment by rutheodora** [comment]
Udah dicek @mhaidarh jadi maksud lo mending yang bagian desciption gw pisahin berdasarkan symbol ama text tapi yang lain tetep ada atau apus semua trus bikin kayak yang punya getgrav itu?

**Comment by mhaidarhanif** [comment]
@rutheodora Iya kalau sempat aja dipisahin. Cukup duplikat dan edit SVG-nya.
Jadi bisa ada:
- symbol + text: 400x200 px
- symbol only: 150x200 px
- text only: 250x200 px

https://getgrav.org/user/pages/media/grav-logos.zip

Ohya tadi gue optimasiin warnanya. Jadi bisa kontras enak di atas hitam ataupun putih. Pake green, cyan blue, blue gray 500.

**Comment by mhaidarhanif** [comment]
@rutheodora Coba Uthe berpendapat apakah Branding Design dan Logo Design dipisahin atau digabung saja.

Kalau digabung, Logo Design ada di dalam/bawah Branding Design. Branding lebih luas, seperti bahasa dan _culture_. Kalau logo hanya bagian grafisnya aja kan.

http://gistbrands.net/brand-vs-logo
http://gomedia.com/zine/insights/difference-between-logo-design-and-branding
http://betterbusinessbrand.com/the-differences-between-a-logo-an-identity-and-a-brand

**Comment by rutheodora** [comment]
@mhaidarh: udah baca, gw udah ngerti konsepnya, tapi gw mau mastiin penulisan laporannya mau gimana point2nya kalo seandaikan gw pisah, berarti isi logo spec cuma gambar logo berbagai ukuran
trus 
yang di branding spec kan ada Shape, Color, Typography kalo pengertian gw:
shape: ngejelasin hubungan logo ama service/product kita (huruf A sama perempatan?)
color: pengertian warna yang gw pake
typography: font yang gw pake buat logo yang text

bener ga sih?

trus nnti gw jelasin font yang dipake web gitu2 juga ga? di branding juga?

**Comment by mhaidarhanif** [comment]
@rutheodora:
Iya bisa begitu, logo spec lebih teknis seputar logo.
Lalu branding spec lebih luas, yang akan orang pandang terhadap kita (atau Arlin dalam hal ini)

Brand –The perceived emotional corporate image as a whole.
Identity – The visual aspects that form part of the overall brand.
Logo – Identifies a business in its simplest form via the use of a mark or icon.
http://justcreative.com/2010/04/06/branding-identity-logo-design-explained

**Comment by mhaidarhanif** [comment]
Koreksi: yang gue di BRAND-SPEC sekarang agak kurang tulisannya memang.
Di BRAND-SPEC sebenarnya cukup ngebahas _style_-nya aja dibanding harus nyebutin spesifik _apa_-nya aja. Jadi lebih abstrak, lebih banyak cerita dan mendesain User Experience (UX).

Sedangkan di LOGO-SPEC lebih konkrit. Ada bentuk dasar, nama serta kode font dan warna, rasio ukurannya. Lebih banyak tampilan dan mendesain User Inteface (UI).

Alhasil, berbagai kategori di masing-masing bisa ada, tapi cara pembuatan dan penyampaiannya berbeda

**Comment by mhaidarhanif** [comment]
Analoginya gini:

Branding menceritakan bahasa yang kita mau itu... kuat namun lembut dan penuh pengertian, memahami situasi terkini dengan cara yang kolaboratif; warna yang dipakai setara dengan kombinasi atau pilihan aneka jalur/pemandangan lalu lintas.

Logo menyajikan branding yang kita mau itu... bernama Arlin, jenis tulisannya seperti jalan raya yang tersambung menggunakan font ini, warnanya dominan ada hijau dan abu-abu dengan kode hex sekian, logogram agak kaku menyimbolkan persimpangan jalan yang jelas dan rapi

**Comment by mhaidarhanif** [comment]
Coba dilanjut dulu ya. Ini berhubungan sama user research yang akan lo lakukan. Kita bisa tau bagaimana pengguna memandang kita, Arlin, dan pengalaman menggunakan aplikasi nantinya.

Ukuran kesuksesan aplikasi kita sejatinya adalah; pengguna mengerti, terbantu, dan _happy_.

cc: @gunadarma-academy/michi

**Comment by rutheodora** [comment]
@mhaidarh darr, yang di pull req, yang logo spec, bagian colornya ke bold semua, lupa gw tutup  boldnya :( gw masih pake < B > pas ngedit td hihihi

**Comment by rutheodora** [comment]
@mhaidarh btw kaya gini bukan buat logo specnya? kalo iya gw mau tutup issue trus lanjut branding

**Comment by mhaidarhanif** [comment]
@rutheodora Sip itu sudah cukup kaya gitu. Silakan tutup issue ini ya.

**Comment by rutheodora** [comment]
doneeee~
