### ISSUE TITLE
Prepare domain registry and VPS for deployment pipeline

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#27]
- Kind: Statement of Work
- Title: Prepare domain registry and VPS for deployment pipeline
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-03-27
- Version: 0.3
# SOW
## Overview

Arlin backend as a node application will be deployed live to the server and connected to the Internet. We're using `arlin.link` as the main production website. Followed by `dev.arlin.link` and `staging.arlin.link` as the development and staging/testing subdomain. This reasoning is because we need to differentiate environment for the deployment pipeline. So our app lanes are safe based on the focus of functionality.
## Tasks
- [x] Register arlin.link via Uniregistry.
- [x] Use CloudFlare as the nameservers to manage the DNS between the domain registry and our server.
- [x] Create initial pm2 config of  `ecosystem.json`, contains application configuration and deployment section for development, staging, and production. Currently each in the same server (DigitalOcean droplet of `mhaidarhanif`: `128.199.216.87`).
- [x] Prepare Nginx config to have the app running via proxy. Via `/etc/nginx/sites-available` and `/etc/nginx/sites-enabled`:
  - arlin.link ~ `arlin.link:9000`
  - arlin.link.staging ~ `staging.arlin.link:9001`
  - arlin.link.development ~ `dev.arlin.link:9002`
- [x] Correspond app folders each:
  - `/home/arlin/app/production`
  - `/home/arlin/app/staging`
  - `/home/arlin/app/development`
- [x] Try to deploy the dummy production version to test the connection.
## Deliverables
- arlin.link is purchased
- The domain registry and our server are connected properly, manageable via CloudFlare.
- The pm2 `ecosystem.json` config is provided here: https://github.com/gunadarma-academy/asde-michi-app/blob/master/ecosystem.json.
- The deployment how-to is provided here: https://github.com/gunadarma-academy/asde-michi-app#deployment
- The dummy production version is working via http://arlin.link or http://arlin.link/api.
## Dependencies

This SOW is actually independent. Also related with #29.
## Assumptions

Still wondering about the best practice here: https://github.com/hapijs/discuss/issues/257
In the middle future of development, we will use practical CI/CD method that utilizes SaaS like Distelli, CircleCI, SemaphoreCI, Wercker, or Shippable; or even PaaS like Heroku to help.

**Comment by mhaidarhanif** [comment]
Earliest setup attempts in local:

![npm-start](https://cloud.githubusercontent.com/assets/235584/14067009/5f09942a-f484-11e5-924b-0ab834455718.png)
![arlin-hello](https://cloud.githubusercontent.com/assets/235584/14067005/4d6d8776-f484-11e5-9a60-4eebf6943299.png)
![arlin-users](https://cloud.githubusercontent.com/assets/235584/14067006/526054fc-f484-11e5-93ad-8a0af1f64d01.png)

**Comment by mhaidarhanif** [comment]
Mid attempts that have various problems (actually):

![setup-1-client](https://cloud.githubusercontent.com/assets/235584/14067012/7a4328b4-f484-11e5-8eb0-8a87ef720e74.png)
![setup-2-server](https://cloud.githubusercontent.com/assets/235584/14067013/7c96c1de-f484-11e5-9ddd-edccc50474d9.png)
![setup-3-client](https://cloud.githubusercontent.com/assets/235584/14067015/85abeace-f484-11e5-9b04-7f28c8725cf9.png)
![setup-4-client](https://cloud.githubusercontent.com/assets/235584/14067016/85ad036e-f484-11e5-98d9-dc846bf746f5.png)
![setup-5-server](https://cloud.githubusercontent.com/assets/235584/14067017/85ae0ce6-f484-11e5-95db-3d915b25e345.png)
![setup-6-server](https://cloud.githubusercontent.com/assets/235584/14067020/85ae5c78-f484-11e5-8c70-82b510791c8b.png)
![setup-7-browser](https://cloud.githubusercontent.com/assets/235584/14067018/85ae0d04-f484-11e5-8cf1-16ecd3b61fee.png)
![setup-8-browser](https://cloud.githubusercontent.com/assets/235584/14067019/85ae2f14-f484-11e5-8248-86d248703391.png)

**Comment by mhaidarhanif** [comment]
Successful attempts that finally work safely:

![resetup-1-client](https://cloud.githubusercontent.com/assets/235584/14067025/a20fa5fc-f484-11e5-9814-382fc8613f93.png)
![resetup-2-client](https://cloud.githubusercontent.com/assets/235584/14067026/a23a33d0-f484-11e5-996c-933e13cd8eda.png)
![resetup-3-server](https://cloud.githubusercontent.com/assets/235584/14067027/a23e96b4-f484-11e5-8ed5-9d98dad24e03.png)

We're now even have a proper monitoring:
![keymetrics](https://cloud.githubusercontent.com/assets/235584/14067065/f0d8b9ca-f485-11e5-9b3f-30a353ba5de6.png)

**Comment by mhaidarhanif** [comment]
@muhpatr I've published my actual attempts on deployment above.
