### ISSUE TITLE
Create Twitter login feature

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#28]
- Kind: Statement of Work
- Title: Create twitter login feature
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-03-27
- Version: 0.2
# SOW
## Overview

Arlin's user must be authenticated to the application via twitter. So, the twitter login feature must be created first before starting to make a basic feature.
## Tasks
- [x] Create Arlin's Twitter application API through <apps.twitter.com>
- [x] Create Twitter server authentication strategy using Hapi and Bell.
- [x] Create the session using cookie.
- [x] Destroy cookie (logout feature)
- [x] Insert the user to MongoDB collection.
## Deliverables

This work will be uploaded to my own repository by the name: [asde-michi-app](https://github.com/muhpatr/asde-michi-app)
## Dependencies

Understand the basic features (#9) and the initial data structures (#10). Also, implement the basic feature (#12).
## Assumptions

Tomorrow will be done.

**Comment by muhpatr** [comment]
The Arlin's twitter application have been created using my own twitter account. The application link is [here](https://apps.twitter.com/app/12129212/show). The application just need the read-only permission to get the username.

**Comment by mhaidarhanif** [comment]
@muhpatr Next time, I think we should have all accounts related to Michi Arlin centralized. Supposedly creating a new Google Account (arlinbymichi@gmail.com or such). Because using personal account is _not authorized to use this endpoint_ by outside user. Needed for deployment in the future with CI/CD SaaS or PaaS as well. Let's discuss this by tomorrow.

cc: @gunadarma-academy/michi

**Comment by muhpatr** [comment]
@mhaidarh I think, using the arlin.link mail account would be great. :)

**Comment by mhaidarhanif** [comment]
@muhpatr That's easy. Working on it. :+1: But unfortunately, the best email app interface in the world is Gmail or Google Apps, so we still need Google Account to manage the email.

**Comment by mhaidarhanif** [comment]
Related to "Create email account on arlin.link" https://github.com/gunadarma-academy/asde-michi/issues/29

**Comment by muhpatr** [comment]
@mhaidarh Please check my on-progress work (4-of-5 have just been done), I've been pushed it to my own repository. Hopefully, it is what our project needed.

**Comment by muhpatr** [comment]
@mhaidarh Need to meet you to do store-to-database work. Because it is depending on the data structures (#10). There is something to be changed on the data structures, I think.

**Comment by mhaidarhanif** [comment]
@muhpatr I'm just starting to check out your work.

Hati-hati pat itu `dev_config.json` jangan sampai ke-commit dan ke-push. Soalnya itu credentials, bahkan levelnya lebih tinggi kalau bukan sama dengan password.

**Comment by mhaidarhanif** [comment]
@muhpatr Please check API and DATA SCHEMA in `asde-michi-app`
https://github.com/gunadarma-academy/asde-michi-app/blob/master/API.markdown
https://github.com/gunadarma-academy/asde-michi-app/blob/master/DATA-SCHEMA.markdown

The "Initial structure for Users, Questions, and Answers" in that https://github.com/gunadarma-academy/asde-michi/issues/10 is already obsolete.

About the user data from Twitter, we should discuss it directly.

**Comment by mhaidarhanif** [comment]
@muhpatr [Follow Up Bump]

Kalo dianggap udah selesai, di-close ya pat. Lalu kita bisa fokus aja di https://github.com/gunadarma-academy/asde-michi/issues/12: Implement the basic features based on the initial data structures.

**Comment by muhpatr** [comment]
@mhaidarh Sudah selesai dengan sedikit perubahan. _id di collection 'Users' nilainya sama dengan twitter_id dari pengguna (Refer to #12). Move on to the next SOW!

**Comment by mhaidarhanif** [comment]
@muhpatr Pat lo dokumentasiin bagaimana initialize database & collection MongoDB-nya. Jadi abis orang clone/pull punya lo, mesti prepare apa.

**Comment by mhaidarh** [comment]
Jadi abis orang clone/pull punya lo, mesti prepare apa.

**Comment by mhaidarhanif** [comment]
@muhpatr Yang paling terbaru banget udah di-push?

**Comment by muhpatr** [comment]
@mhaidarh Belum di-push, masih dirapihin. Dokumentasi ttg initialize database dan collection nanti ditaruh di repo pribadi aja dulu ya.

**Comment by muhpatr** [comment]
@mhaidarh Saat ini sedang cari tahu gimana caranya simpan data tanggal ke mongoDB

**Comment by muhpatr** [comment]
@mhaidarh ternyata cuma new Date() -___-

**Comment by mhaidarhanif** [comment]
@muhpatr Oke yang penting kita ada catatan gimana pake repo dengan database-nya. Karena metode lo dan gue bisa jadi lumayan beda caranya.

**Comment by mhaidarhanif** [comment]
@muhpatr Barusan gue nemu contoh:
https://github.com/p-meier/hapi-rest-mongo

**Comment by muhpatr** [comment]
@mhaidarh Dar, Tenang. Gue juga refer ke web itu buat bikin API. HAHAHAHA :")

**Comment by muhpatr** [comment]
@mhaidarh Sudah di push ke repo gue ya. Sudah pull request juga ke repo asde-michi-app yang utama.

**Comment by mhaidarhanif** [comment]
@muhpatr hahahah Iya gue nyadarin lagian tipikal gitu. Kayak sedih. hahah.
Oke sip.
