### ISSUE TITLE
Create email account on arlin.link

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#29]
- Kind: Statement of Work
- Title: Create email account on arlin.link
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-03-27
- Version: 0.1
# SOW
## Overview

Create a centralized email account on arlin.link for various purposes. Email and Twitter are the main priorities.
## Tasks
- [x] Create Google Account: arlin.by.michi@gmail.com
- [x] Verify domain in Zoho through CloudFlare with CNAME and TXT
- [x] Create Zoho Mail account: admin@arlin.link
## Deliverables

All team members can access arlin.by.michi@gmail.com or admin@arlin.link
## Dependencies

The domain is ready and connected via CloudFlare.

**Comment by muhpatr** [comment]
@mhaidarh I want patr@arlin.link as my Arlin's mail account. Hehehe.

**Comment by mhaidarhanif** [comment]
@muhpatr "Hehehe" banget pat? :)))
