### ISSUE TITLE
Create API for posting and showing the questions

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#34]
- Kind: Statement of Work
- Title: Create API for posting and showing the questions
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-03-31
- Version: 0.3
# SOW
## Overview

All Arlin visitor can see all questions. After logged in to Arlin via Twitter, user can post the question. Thus, I will create API for showing all questions, and posting the question from the authenticated user.
## Tasks
- [ ] Create 'Questions' collection (Refer to [DATA-SCHEMA](https://github.com/gunadarma-academy/asde-michi-app/blob/d1eba5d96689cac2007c50aab166f05a797c4310/DATA-SCHEMA.markdown) document)
- [ ] Create questions API for getting all questions
- [ ] Create questions API for getting specific question
- [ ] Create questions API for posting user's question
- [ ] Create questions API for deleting user's question
- [ ] Create questions API for updating user's question

All questions API refer to this [API](https://github.com/gunadarma-academy/asde-michi-app/blob/d1eba5d96689cac2007c50aab166f05a797c4310/API.markdown) document.

Mainly refer to "Implement the basic features based on the initial data structures" (https://github.com/gunadarma-academy/asde-michi/issues/12)
## Deliverables

This work will be uploaded to my own repository by the name: [asde-michi-app](https://github.com/muhpatr/asde-michi-app)
## Dependencies

For creating the posting, deleting, and updating API, the user need to be authenticated via Twitter. So, this work will be done after creating the Twitter login feature (#28).
## Assumptions

This work will be done for estimated time of one week.

**Comment by mhaidarhanif** [comment]
@muhpatr Sering-sering pas tiap lo commit langsung di-push ya pat. :+1:

**Comment by mhaidarhanif** [comment]
@muhpatr Sama inget terus untuk `pull upstream`.
"Your branch is 2 commits behind `gunadarma-academy:master`."

**Comment by mhaidarhanif** [comment]
@muhpatr You can close this issue for now.

**Comment by muhpatr** [comment]
This work has not been done yet, since I'm facing some problem with node.js. Sorry for that.
This work will be continued by @mhaidarh.

**Comment by mhaidarhanif** [comment]
Affirmative.
