### ISSUE TITLE
Fill out Master Test Plan document (part A)

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#36]
- Kind: Statement of Work
- Title: Fill out Master Test Plan document
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-04-07
- Version: 0.2
# SOW
## Overview

Create Master Test Plan document for the first version of Arlin. I will work with @rutheodora to create this document. The document adapted from [Master Test Plan (v061111) by Northwestern University Information Technology](http://www.it.northwestern.edu/bin/docs/project-framework/Master_Test_Plan_v061111.docx) and [already converted here](https://github.com/gunadarma-academy/asde-michi-test/blob/master/master-test-plan.markdown).
## Tasks
- [x] Define test scope
- [x] Define test features
- [x] Define test inputs/outputs
- [x] Define test strategies
- [x] Define test strategy responsibilities
- [x] Define test roles and responbilities
- [x] Define test milestones
## Deliverables

The document will be uploaded to [asde-michi-test](https://github.com/gunadarma-academy/asde-michi-test) submodule.
## Assumptions

This work will be done (for estimated time) before Friday, April 8th, 2016.

**Comment by mhaidarhanif** [comment]
cc: @rutheodora

**Comment by rutheodora** [comment]
@mhaidarh dar. kita yg ga diperluin skrg itu yg mana ya? unit test, functional, atau integration?

**Comment by mhaidarhanif** [comment]
Selain UAT, belum diperluin yang itu.

**Comment by muhpatr** [comment]
@mhaidarh I and @rutheodora need help for defining test inputs/outputs. Can you fill this section in the document, later?

**Comment by mhaidarhanif** [comment]
Yes I can

**Comment by mhaidarhanif** [comment]
@muhpatr @rutheodora Test input dan output saat ada step _Given_ dan _Then_, pada awal dan akhir tiap scenario dalam feature. Jadi sebenernya bisa diserahin ke _feature files_. Tinggal bilang semua test input/output tersebut ada di dalam dokumen terpisah.

**Comment by rutheodora** [comment]
@mhaidarh @muhpatr okeey, berarti isinya paragraf singkat doang ya nantinyaa yang buat ngarahin ke dokumen skenario

**Comment by mhaidarhanif** [comment]
@rutheodora Iya bisa kita adaptasikan seperti itu.

**Comment by muhpatr** [comment]
@mhaidarh Please check my last commit, thanks :+1:

**Comment by mhaidarhanif** [comment]
@muhpatr Checking it...

**Comment by mhaidarhanif** [comment]
@muhpatr Checked out and improved. Please pull the latest and close this issue.
