### ISSUE TITLE
Fill out Master Test Plan document  (part B)

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#37]
- Kind: Statement of Work
- Title: Fill out Master Test Plan document
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-04-07
- Version: 0.2
# SOW
## Overview

Create Master Test Plan document for the first version of Arlin. I will work with @rutheodora to create this document. The document adapted from [Master Test Plan (v061111) by Northwestern University Information Technology](http://www.it.northwestern.edu/bin/docs/project-framework/Master_Test_Plan_v061111.docx) and [already converted here](https://github.com/gunadarma-academy/asde-michi-test/blob/master/master-test-plan.markdown).
## Tasks
- [x] Define test scope
- [x] Define test features
- [ ] Define test inputs/outputs
- [x] Define test strategies
- [x] Define test strategy responsibilities
- [x] Define test roles and responsibilities
- [x] Define test milestones
## Deliverables

The document will be uploaded to [asde-michi-test](https://github.com/gunadarma-academy/asde-michi-test) submodule.
## Assumptions

This work will be done (for estimated time) before Friday, April 8th, 2016.

**Comment by rutheodora** [comment]
@mhaidarh, @ekkyvalent for User Interface Test on Test Strategy section, please help us by providing/describing the explanation 

@muhpatr

**Comment by mhaidarhanif** [comment]
Roger that

**Comment by rutheodora** [comment]
@mhaidarh : untuk yang **Define test inputs/outputs** mungkin bisa diserahkan ke haidar untuk pengisiannya

**Comment by mhaidarhanif** [comment]
@rutheodora I/O test ada di tiap awal dan akhir scenario, pada saat Given dan Then.

**Comment by mhaidarhanif** [comment]
@rutheodora Checked out and improved. Please pull the latest and close this issue.
