### ISSUE TITLE
Create scenario test document for Login and Logout feature

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#38]
- Kind: Statement of Work
- Title: Create Scenario test document for Login and Logout features
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-04-07
- Version: 0.2
# SOW
## Overview

Create Scenario test for Login and Logout feature using [Gherkin syntax](https://cucumber.io/docs/reference). This test based on some scenario condition for Login and Logout feature.
## Tasks
- [x] Define the Login scenario
- [x] Define the Login scenario description
- [x] Define the Logout scenario
- [x] Define the Logout scenario
- [x] Create the Login scenario document
- [x] Create the Logout scenario document
## Deliverables

The document will be uploaded to [asde-michi-test](https://github.com/gunadarma-academy/asde-michi-test) submodule.
## Dependencies

The master test plan needs to be done first (#36 and #37).
## Assumptions

This work will be done (for estimated time) before Friday, April 8th, 2016.

**Comment by muhpatr** [comment]
login.feature

```
Feature: User is able to login with username and password

Scenario: User wants to use Arlin
  Given User has filled the Username field
  And User has not filled the Password field
  When User clicks the Login button
  Then User fails to log in

Scenario: User wants to use Arlin
  Given User has not filled the Username field
  And User has filled the Password field
  When User clicks the Login button
  Then User fails to log in

Scenario: User wants to use Arlin
  Given User has not filled the Username field
  And User has not filled the Password field
  When User clicks the Login button
  Then User fails to log in

Scenario: User wants to use Arlin
  Given User has filled the correct username in Username field
  And User has filled the wrong password in Password field 
  When User clicks the Login button
  Then User fails to log in

Scenario: User wants to use Arlin
  Given User has filled the wrong username in Username field
  And User has filled the correct password in Password field 
  When User clicks the Login button
  Then User fails to log in

Scenario: User wants to use Arlin
  Given User has filled the wrong username in Username field
  And User has filled the wrong password in Password field 
  When User clicks the Login button
  Then User fails to log in

Scenario: User wants to use Arlin
  Given User has filled the correct username in Username field
  And User has filled the correct password in Password field 
  When User clicks the Login button
  Then User get the Arlin session (cookies) and is able to use Arlin functionality

Scenario: User wants to use Arlin
  Given User clicks the Twitter Login button
  And User has the Twitter token authorization 
  When Twitter page has been redirected to Arlin
  Then User get the Arlin session (cookies) and is able to use Arlin functionality

Scenario: User wants to use Arlin
  Given User clicks the Twitter Login button
  And User does not have the Twitter token authorization 
  When Twitter page has been redirected to Arlin
  Then User does not get the Twitter token authorization and fails to log in

Scenario: User wants to use Arlin
  Given User has the Arlin session (cookies)
  When User opens the Login page
  Then User will be redirected to Arlin main page and is able to use Arlin functionality
```

**Comment by muhpatr** [comment]
`logout.feature`

```
Feature: Logout

Scenario: User wants to log out from Arlin website
  Given User has the Arlin session (cookies)
  When User clicks Logout button
  Then User is able to log out from Arlin website

Scenario: User wants to log out from Arlin website
  Given User does not have the Arlin session (cookies)
  When User clicks Logout button
  Then User will be redirected to Arlin main page
```

**Comment by muhpatr** [comment]
cc: @mhaidarh @rutheodora 
Please, check my work.

And also, I want to ask a question, is this Scenario test document will be splitted by each features or will be merged in one document? Can you create one Scenario test template document that have been styled by Markdown to match the template by Gherkin?

**Comment by muhpatr** [comment]
cc: @mhaidarh _try to mention again_

**Comment by mhaidarhanif** [comment]
@muhpatr Already checked and modified.

**Comment by mhaidarhanif** [comment]
@muhpatr All scenarios in each feature are all combined in one document. We just need to separate each features in separated documents. They don't need Markdown syntax.

**Comment by muhpatr** [comment]
@mhaidarh Thank you for the correction!

**Comment by muhpatr** [comment]
The document has been commited. May I close this issue? @mhaidarh

**Comment by mhaidarhanif** [comment]
@muhpatr Hold it up.

**Comment by mhaidarhanif** [comment]
@muhpatr You need to improve it a little, make each similar scenarios as a single scenario with variables.

**Comment by mhaidarhanif** [comment]
@muhpatr You might need to tidy up your login feature file.

**Comment by muhpatr** [comment]
@mhaidarh but there is some different condition. could not be generalized into a variable (because of different 'Then')

**Comment by mhaidarhanif** [comment]
@muhpatr But some of them still could be generalized, for top **Scenario: User wants to use Arlin** and bottom scenario, separated.

**Comment by mhaidarhanif** [comment]
@muhpatr You also need to be specific on your Scenario title. **User wants to use Arlin** is too ambiguous.

**Comment by mhaidarhanif** [comment]
Try to combine all scenarios which have **Then user fails to log in** first, then move on to another.
