### ISSUE TITLE
Create scenario test document for main features

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#39]
- Kind: Statement of Work
- Title: Create Scenario test document for Posting Answer, Posting Question Feature, Retrieve Questions, and Retrieve Question’s Answers features
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-04-07
- Version: 0.2
# SOW
## Overview

Create Scenario test for Posting Answer, Posting Question Feature, Retrieve Questions, and Retrieve Question’s answers feature using [Gherkin syntax](https://cucumber.io/docs/reference). This test based on some scenario condition for Login and Logout feature.
## Tasks
- [x] Define the Posting Answer scenario
- [x] Define the Posting Answer description
- [x] Define the Posting Question scenario
- [x] Define the Posting Question description
- [x] Define the List Questions scenario
- [x] Define the List Questions description
- [x] Define the List Question’s answers scenario
- [x] Define the List Question’s answers description
- [x] Create the Posting Answer scenario document
- [x] Create the Posting Question scenario document
- [x] Create the List Questions scenario document
- [x] Create the List Question’s answers scenario document
## Deliverables

The document will be uploaded to [asde-michi-test](https://github.com/gunadarma-academy/asde-michi-test) submodule.
## Dependencies

The master test plan needs to be done first (#36 and #37).
## Assumptions

This work will be done (for estimated time) before Friday, April 8th, 2016.

**Comment by rutheodora** [comment]
`post_question.feature`

```
Feature: Posting a question

Scenario Outline: User post a question
  Given user <title> filled the title field
  And user <desc> filled the description field
  When user click the submit button
  Then user is <post> to post a question

  Examples:
    | title   | desc    | post     |
    | has     | has     | able     |
    | has     | not has | not able |
    | has not | has     | not able |
    | has not | has not | not able |
```

**Comment by rutheodora** [comment]
`post_answer.feature`

```
Feature: Posting Answer

  Scenario: User wants to answer the question
    Given User has filled the answer field
    When User clicks the submit button
    Then User is able to answer the question

  Scenario: User wants to answer the question but not filled the answer field
    Given User has not filled the answer field
    When User clicks the submit button
    Then User is not able to answer the question
```

**Comment by rutheodora** [comment]
`list_questions.feature`

```
Feature: List all available questions

  Scenario: User is able to see all the available questions
    Given Application read the Question database
    When User accesses the home page
    Then User is able to see all questions
```

**Comment by rutheodora** [comment]
`list_questions_answers.feature`

```
Feature: Retrieve Question’s Answer

  Scenario: User is able to read the answer of the question
    Given App read the Question database and its Answer database
    When User clicks the chosen Question box
    Then User is able to read the question's answer
```

**Comment by rutheodora** [comment]
@mhaidarh @muhpatr : cek yang ini juga yaw :3

**Comment by mhaidarhanif** [comment]
@rutheodora Already checked and modified.

**Comment by rutheodora** [comment]
`post_question.feature`

```
Feature: Posting Question

Scenario Outline: User post a question
  Given user <title> filled the title field
  And user <desc> filled the description field
  When user click the submit button
  Then user is <post> to post a question

  Examples:
    | title   | desc    | post     |
    | has     | has     | able     |
    | has     | not has | not able |
    | has not | has     | not able |
    | has not | has not | not able |
 ```

Title Description

**Comment by mhaidarhanif** [comment]
@rutheodora Di atas bahkan udah gue modif the.
https://github.com/gunadarma-academy/asde-michi/issues/39#issuecomment-206734132

**Comment by rutheodora** [comment]
@mhaidarh ... td belum kerefresh xD

**Comment by mhaidarhanif** [comment]
@rutheodora Yowis lo edit semua yang belum.

**Comment by mhaidarhanif** [comment]
@rutheodora Checked out and improved. Please pull the latest and close this issue.
