### ISSUE TITLE
Ekky's front end skills enhancement

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi#4]
- Kind: Statement of Work
- Title: Ekky's front end skills enhancement
- Author: Ekky Pramana
- Affiliation: Michi
- Date: 2016-03-17
- Version: 0.1
# SOW
## Overview

Since my front end knowledge is a little bit rusty I decided to have a little warm up prior to the main task with the help of a lot of sources such as [Codecademy](https://www.codecademy.com/learn). I recommend @rutheodora to check them (again if you already did) because it will greatly help us on the front side.
## Tasks
- [x] re-re-relearn anything important.
- [x] further learn about how to make a responsive page.
- [x] create my own personal web pages. 
## Deliverables

This practice will span across our entire project. ETA for the personal web page: 1 week.
## Assumptions

The final work will be uploaded for everyone to see.
