### ISSUE TITLE
Create and fill out the UAT document for survey questionnaire (part A)

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#40]
- Kind: Statement of Work
- Title: Create and fill out the UAT document for survey questionnaire
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-04-07
- Version: 0.1
# SOW
## Overview

Prepare all the questions before doing the UAT test. I will work with @muhpatr to create this document.
## Tasks
- [ ] Make questions based on User Interface of Arlin
- [ ] Make questions based on Content of Arlin
- [ ] Make questions based on Ease of Use of Arlin
- [ ] Make questions based on Usability of Arlin
- [ ] Create the UAT questionnaire document
## Deliverables

The document will be uploaded to [asde-michi-test](https://github.com/gunadarma-academy/asde-michi-test) submodule and  the UAT test can be performed after this.
## Assumptions

This work will be done (for estimated time) before Sunday, April 10th, 2016.
