### ISSUE TITLE
Create and fill out the UAT document for survey questionnaire (part B)

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#41]
- Kind: Statement of Work
- Title: Create and fill out the UAT document for survey questionnaire
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-04-07
- Version: 0.1
# SOW
## Overview

Prepare all the questions before doing the UAT test. I will work with @rutheodora to create this document.
## Tasks
- [x] Make questions based on User Interface of Arlin
- [x] Make questions based on Content of Arlin
- [x] Make questions based on Ease of Use of Arlin
- [x] Make questions based on Usability of Arlin
- [ ] Create the UAT questionnaire document
## Deliverables

The document will be uploaded to [asde-michi-test](https://github.com/gunadarma-academy/asde-michi-test) submodule and  the UAT test can be performed after this.
## Assumptions

This work will be done (for estimated time) before Sunday, April 10th, 2016.

**Comment by muhpatr** [comment]
@rutheodora thank you for creating this SOW :D

**Comment by rutheodora** [comment]
@muhpatr you're welcome ;), check this doc : https://docs.google.com/document/d/1US7PO45dlNsEzQYPxsd2CRt2bZ3QhMa1DSs6zPblODI/edit 
I've already translated 10 questions. I think I will create a new .md file in asde-michi-test folder to put the questionnaire.

**Comment by rutheodora** [comment]
@muhpatr:
![chocolate-pancake-cake-101](https://cloud.githubusercontent.com/assets/17141470/14403165/618decc6-fe77-11e5-9b66-876af0eb6382.jpg)
btw kita ga jadi ke perpus seberang?

**Comment by muhpatr** [comment]
@rutheodora Already translated my part. What a beautiful pancake.........
