### ISSUE TITLE
Prepare the slide for final presentation

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi#46]
- Kind: Statement of Work
- Title: Prepare the slide for final presentation
- Author: <Your Full Name>
- Affiliation: Michi
- Date: 2016-04-13
- Version: 0.1
# SOW
## Overview

I will prepare the slide for the finals which will make use of [this repo](https://github.com/gunadarma-academy/asde-michi-slide) as the base. The final result will not differ much with the exception of complete features explanation.
## Tasks
- [x] Create the slide outline
- [x] Fill in the slide details
- [x] Divide the slide into four, neat, streamlined presentation
- [x] Complete the aesthetics
## Deliverables

The slide will be created in presentable formats (Google Slide and PDF), then the files or information regarding that will be commited to `asde-michi-slide` repository. Presumably in the `README`.
## Assumptions

Will eventually finished by the final (lel).

**Comment by mhaidarhanif** [comment]
![final is coming](https://cdn.meme.am/instances/500x/67834780.jpg)

**Comment by mhaidarhanif** [comment]
Assigned for every member (@gunadarma-academy/michi)

**Comment by mhaidarh** [comment]
Arlin - Pitch Deck: http://bit.ly/arlindeck

**Comment by mhaidarhanif** [comment]
Arlin - Pitch Deck: http://bit.ly/arlindeck
