### ISSUE TITLE
Learn Vue.js for frontend app

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi#47]
- Kind: Statement of Work
- Title: Learn Vue.js for frontend app
- Author: Ekky Pramana
- Affiliation: Michi
- Date: 2016-04-19
- Version: 0.1
# SOW
## Overview

Here is the part where I further learn about front-end development, which involves Vue.js, Reactive Components for Modern Web Interfaces.
## Tasks
- [x] Learn asic Vue JS syntax and stuffs 
- [x] Learn authentication process using [this](https://auth0.com/blog/2015/11/13/build-an-app-with-vuejs/) method
- [x] Other things will be added when necessary
## Assumptions

This should be done collectively with the building process.

**Comment by mhaidarhanif** [comment]
[package-list.txt](https://github.com/gunadarma-academy/asde-michi/files/225742/package-list.txt)
