### ISSUE TITLE
Streamline testing suite for backend and frontend

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#48]
- Kind: Statement of Work
- Title: Streamline testing suite for backend and frontend
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-04/19
- Version: 0.2
# SOW
## Overview

A testing suite that is intended for Unit/Functional tests for both `backend` and `frontend` using Mocha, Chai, Jasmine, Karma, or other selected tools. Even Integration of End-to-End tests using Cucumber and its Gherkin syntax. 
## Tasks
- [x] Upgrade https://github.com/gunadarma-academy/asde-michi-test
- [x] Change `app` repo to `backend`.
- [x] Change `web` repo to `frontend`.
- [x] Make `backend` and `frontend` (as the app) repo as submodules.
- [x] Try to run tests when the app is running.
- [x] Integrate the tests and app on Continous Integration server/SaaS using Codeship and Snap CI (also for Continuous Delivery).
  - [x] Add the project SSH key into the server when needed (for use with `pm2` deployment).
## Deliverables
- Test module (https://github.com/gunadarma-academy/asde-michi-test) is able to test both backend (https://github.com/gunadarma-academy/asde-michi-backend) and frontend (https://github.com/gunadarma-academy/asde-michi-frontend).
- The apps are all integrated, tested, and delivered with CI/CD anytime when we push to respective branch.
- The report of the test result can be generated.
- The dynamic results are on https://snap-ci.com/gunadarma-academy/asde-michi-test.
## Dependencies

Migration to a new framework (https://github.com/gunadarma-academy/asde-michi-backend/pull/5) is finished.

**Comment by mhaidarhanif** [comment]
Along with https://github.com/gunadarma-academy/asde-michi-test/commit/2091fdd72d17b112aabcd0545e4aa1c4bacf313a, this SOW is done.
