### ISSUE TITLE
Patria's Node.js learning

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#5]
- Kind: Statement of Work
- Title: Patria's Node.js learning
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-03-18
- Version: 0.1
# SOW
## Overview

Since I don't know about Node.Js, I want to learn about this platform via tutorial on some websites.
## Tasks
- [x] install node.js
- [x] learn about node.js (follow the tutorial)
- [x] create a small node.js program
## Deliverables

This practice will span across our entire project. ETA for the learning project: less than 1 week.

**Comment by muhpatr** [comment]
I'm starting to learn about JavaScript & Node.JS from this website: http://nodeschool.io/
