### ISSUE TITLE
Product Launch of Arlin v2

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#50]
- Kind: Epic
- Title: Product Launch of Arlin v2
- Author: Arlin
- Affiliation: Michi
- Date: 2016-04-19
- Version: 0.1
# SOW
## Overview

Launch Arlin v2, with better and faster modern app.
## Tasks

**Progressing**
- [x] Use Feathers and Vue.js for backend and frontend
- [x] Commence User Acceptance Test (UAT)
- [x] Create success criteria for this project
- [x] Create user manual

**Final**
- [x] Group deliverables report of each SOW
- [x] Create presentation slide
## Deliverables

The finished Arlin v2 is delivered at http://arlin.link (that is previously at http://dev.arlin.link and http://staging.arlin.link). Also presented to the class.
## Dependencies

(View them with ZenHub)

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi This _**EPIC**_ is made.

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi Closed for today's exam.
