### ISSUE TITLE
Create UAT success criteria for this project

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#51]
- Kind: Statement of Work
- Title: Create success criteria for this project
- Author: Patria and Ruth
- Affiliation: Michi
- Date: 2016-04-20
- Version: 0.1
# SOW
## Overview

Define the success criteria for our project based on the User Acceptance Test
## Tasks
- [x] Create the success criteria document 
- [x] Define the success criteria in UAT section
- [x] Put some graph or table to the documentation
## Deliverables

To know if this project can be accepted by the user
## Dependencies
#58 and #59 must be done first

**Comment by mhaidarhanif** [comment]
@muhpatr @rutheodora 
Bisa dibuat atau ditambahkan dalam `PRODUCT.markdown` di `docs`.
Seperti penjelasan yang udah dikasi tau ke Bu Lulu.
Dalam proyek Arlin, kriteria sukses utama untuk user berdasarkan UAT.
Nanti gue dan @ekkyvalent naro kriteria sukses juga yang terkait technical atau application.

**Comment by rutheodora** [comment]
@mhaidarh @muhpatr dar berhubung gw udah ada hasil analisis di https://github.com/gunadarma-academy/asde-michi-test/blob/master/USER-ACCEPTANCE-TEST-ANALYSIS.markdown untuk yang kriteria sukses untuk UATnya ngambil kalimat2 yang udah gw buat disitu dan cuma nambahin **kalo target minimal kita 70%**

**Comment by mhaidarhanif** [comment]
@rutheodora Oke sip.
