### ISSUE TITLE
Create user manual of Arlin

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#52]
- Kind: Statement of Work
- Title: Create user manual of Arlin
- Author: Patria and Ruth
- Affiliation: Michi
- Date: 2016-04-20
- Version: 0.2
# SOW
## Overview

Make a user manual documentation. The document will explain about how to use the Arlin website
## Tasks
- [x] Discuss with @muhpatr about the documentation
- [x] Make the user manual documentation
- [x] Upload the documentation to our repo
## Deliverables

A user manual document in a form of PDF named 'USER-MANUAL'.
## Assumptions

this task needs to be done to help the user when having a problem when using the Arlin.

**Comment by muhpatr** [comment]
It's done! The user manual can be found at [here](https://github.com/gunadarma-academy/asde-michi/blob/master/docs/USER-MANUAL.pdf). Onto the next one!
