### ISSUE TITLE
Test backend app with Mocha and Chai

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#54]
- Kind: Statement of Work
- Title: Test backend app with Mocha and Chai
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-04-19
- Version: 0.1
# SOW
## Overview

The backend app that is now using Vue.js needs to be unit/functionally tested with selected test suite. Presumably JSHint, Mocha, and Chai.
## Tasks
- [x] Properly look up for test scripts intended for unit/functional testing.
- [x] Try to automate the tests even more with CI/CD.
- [x] Practice BDD/TDD along with this intention.
- [x] Create more tests along with added functionalities.
## Deliverables

The test scripts can be run with `npm test`. The report (can be in various format) is then generated each time it's run. If tried and possible, automate this with CI/CD (refer to https://github.com/gunadarma-academy/asde-michi/issues/48).
## Dependencies

Progressed along with Streamline testing suite for backend and frontend (https://github.com/gunadarma-academy/asde-michi/issues/48) and Implement backend based on the new designated API and data (https://github.com/gunadarma-academy/asde-michi/issues/49).
## References

Should work and passes all tests in order to make it a quality project.
- http://docs.feathersjs.com
- http://mochajs.org
- http://chaijs.com
