### ISSUE TITLE
Implement frontend based on the new designated routes, API, and data

### ISSUE THREAD

**Issue by ekkyvalent** [gunadarma-academy/asde-michi#55]
- Kind: Statement of Work
- Title: Implement frontend based on the new designated routes, API, and data
- Author: Ekky Pramana
- Affiliation: Michi
- Date: 2016-04-22
- Version: 0.2
# SOW
## Overview

Implement frontend features based on the new designated API endpoints and data schema/structures. Should prove the data process are working correctly in the app.
## Tasks
- [x] Make all the data collection as services, can be accessed internally or externally.
- [x] Authentication is using JWT (JavaScript Web Token).

**User**
- [x] Implement user authentication.
- [x] Visitor can sign up and sign in via `/signup` and `/signin`.
- [x] User can have a username and password as credentials.
- [x] User credentials that already set by users are stored.

**Get all questions**
- [ ] User can see all the public questions/threads via `/` or `/questions`.

_Below are the functionalities when a user is authenticated_

**Ask a question**
- [ ] User can ask a question via `/questions/ask`.
- [ ] Questions that already posted by users are stored and listed at `/questions/:id`.

**Edit a question**
- [ ] User can edit a question via `/questions/:id/edit`.
- [ ] Questions that already edited by users are stored and still listed at `/questions/:id`.

**Delete a question**
- [ ] User can ask delete their own question via `/questions/:id/delete`.

**Answer a question**
- [ ] Other user can answer/comment on a question/thread via `/questions/:id/create`.
- [ ] Answers that already be given by users are listed below the answers. Optionally can be accessed with `/questions/:question_id#:answer_id`
## Deliverables
- [x] All of the authorized routes can be used and accessed by the user.
- [ ] All of the expected data are able to be sent to, retrieved from, and modified.
- [ ] With the backend app, it should work as expected.
- [ ] ROUTES documentation in parent repo docs.
## Dependencies

Understand the basic features (https://github.com/gunadarma-academy/asde-michi/issues/9) and the initial data structures (https://github.com/gunadarma-academy/asde-michi/issues/10).
## Assumptions

This basically makes the app and UI functionally correct.

**Comment by mhaidarhanif** [comment]
@ekkyvalent I've added one important deliverable about ROUTES document.
