### ISSUE TITLE
Create the online spreadsheets for calculating and analyzing the questionnaire

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#57]
- Kind: Statement of Work
- Title: Create the online spreadsheets for calculating and analyzing the questionnaire
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-04-20
- Version: 0.1
# SOW
## Overview

This is part of the final task of UAT testing. After the questionnaires have been spread, the questionnaire response must be calculated and the result shall be analyzed. 
## Tasks
- [x] Make the online spreadsheets
- [x] Put the calculation formula in online spreadsheets
- [x] Put the other details/explanation 
- [x] Share the online spreadsheets with @muhpatr 
## Deliverables

Must be done today.
## Assumptions

This is the preparation for the UAT result documentation. so this work needs to be done.

**Comment by rutheodora** [comment]
@muhpatr mohon cek email, ada yang gw share, thx
