### ISSUE TITLE
Calculate and analyze the result of online questionnaire (part A)

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#58]
- Kind: Statement of Work
- Title: Calculate and analyze the result of online questionnaire (part A)
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-04-20
- Version: 0.1
# SOW
## Overview

This is the final task of UAT testing. After the questionnaires have been spread, me and @muhpatr will put the responses to online spreadsheets and analyze the result.
## Tasks
- [x] Put and calculate the questionnaire response to the provided online spreadsheets
- [x] Make and check the result table
- [x] Generate the Pie Chart from the responses 
- [x] Create the UAT result documentation on our repo
- [x] Move the result from online spreadsheets to UAT result documentation
## Dependencies
#44 #45 #57 must be done first.

**Comment by muhpatr** [comment]
The result can be seen on the success criteria document.

**Comment by rutheodora** [comment]
![img_1_respondents_by_age](https://cloud.githubusercontent.com/assets/17141470/14762787/18123240-09ae-11e6-97cb-d48982ca57c4.png)
![img_2_respondents_by_city](https://cloud.githubusercontent.com/assets/17141470/14762786/18121256-09ae-11e6-9dc2-fa3d4590ac59.png)
![img_3_respondents_by_gender](https://cloud.githubusercontent.com/assets/17141470/14762783/1810ba8c-09ae-11e6-8941-a55fbdc1d37f.png)
![img_4_respondents_by_education](https://cloud.githubusercontent.com/assets/17141470/14762784/1811b360-09ae-11e6-842a-1323c1891ae9.png)
![img_5_respondents_by_work_field](https://cloud.githubusercontent.com/assets/17141470/14762785/181223e0-09ae-11e6-905d-96193a25a85b.png)
![img_6_travelling_transportation](https://cloud.githubusercontent.com/assets/17141470/14762788/183e9e3e-09ae-11e6-98d2-b8ac498107a8.png)
![img_7_frequency_of_confusion](https://cloud.githubusercontent.com/assets/17141470/14762789/18446620-09ae-11e6-9e64-b411f3c56542.png)
![img_8_action_of_confusion](https://cloud.githubusercontent.com/assets/17141470/14762782/180d7930-09ae-11e6-811b-c96d60c7c18c.png)

cc: @muhpatr

**Comment by muhpatr** [comment]
It's done! The document can bee seen [here](https://github.com/gunadarma-academy/asde-michi-test/blob/master/USER-ACCEPTANCE-TEST-ANALYSIS.markdown).

**Comment by rutheodora** [comment]
![img_9_likert_scale_average](https://cloud.githubusercontent.com/assets/17141470/14813423/cffe8b00-0bcb-11e6-9106-b88ff0527880.png)
![img_10_success_variable](https://cloud.githubusercontent.com/assets/17141470/14813422/cffdf0a0-0bcb-11e6-8ea5-3f7ec7076d1c.png)
