### ISSUE TITLE
Calculate and analyze the result of online questionnaire (part B)

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#59]
- Kind: Statement of Work
- Title: Calculate and analyze the result of online questionnaire (part A)
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-04-20
- Version: 0.1
# SOW
## Overview

This is the final task of UAT testing. After the questionnaires have been spread, me and @rutheodora will put the responses to online spreadsheets and analyze the result.
## Tasks
- [x] Put and calculate the questionnaire response to the provided online spreadsheets
- [x] Make and check the result table
- [x] Generate the Pie Chart from the responses 
- [ ] Create the UAT result documentation on our repo
- [ ] Move the result from online spreadsheets to UAT result documentation
## Dependencies
#44 #45 #57 must be done first.

**Comment by muhpatr** [comment]
The result can be seen on the success criteria document.

**Comment by muhpatr** [comment]
![data-analysis-uat](https://cloud.githubusercontent.com/assets/4652284/14762705/90b0e3b6-09ab-11e6-8bee-d61c2853a3c7.png)

**Comment by muhpatr** [comment]
![data-result](https://cloud.githubusercontent.com/assets/4652284/14762717/e44b888c-09ab-11e6-8493-66d994cff855.png)

**Comment by mhaidarhanif** [comment]
:+1:

**Comment by muhpatr** [comment]
![data-gender](https://cloud.githubusercontent.com/assets/4652284/14762814/e8a12880-09ae-11e6-98f5-ab195c54a631.png)
![data-city](https://cloud.githubusercontent.com/assets/4652284/14762818/edf1a2ce-09ae-11e6-8b87-a69898d3c085.PNG)
![data-age](https://cloud.githubusercontent.com/assets/4652284/14762821/f4660884-09ae-11e6-9ddf-78f0ee8a0765.PNG)
![data-education](https://cloud.githubusercontent.com/assets/4652284/14762827/fee08668-09ae-11e6-8d48-b245189304e3.PNG)
![data-work-field](https://cloud.githubusercontent.com/assets/4652284/14762829/0374b9c4-09af-11e6-98e5-1b735da841f8.PNG)
![data-travelling-transportation](https://cloud.githubusercontent.com/assets/4652284/14762832/09ef3dba-09af-11e6-8c92-c598978c817b.PNG)
![data-frequency-confusion](https://cloud.githubusercontent.com/assets/4652284/14762834/0f6b56d4-09af-11e6-8ee2-df9ca8244f01.PNG)
![action-confusion](https://cloud.githubusercontent.com/assets/4652284/14762836/1373a9a2-09af-11e6-8a86-b7cbcea684a0.PNG)

**Comment by muhpatr** [comment]
It's done! The document can bee seen [here](https://github.com/gunadarma-academy/asde-michi-test/blob/master/USER-ACCEPTANCE-TEST-ANALYSIS.markdown).
