### ISSUE TITLE
Create a wireframe for Arlin's website

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#6]
- Kind: Statement of Work
- Title: Create a wireframe for Arlin's website
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-03-18
- Version: 0.3
# SOW
## Overview

I will create a wireframe for our web project. Later, this wireframe will help @muhpatr and @mhaidarh while developing Arlin's website. The design itself must get @ekkyvalent 's approval first.
## Tasks
- [x] Sketching the wireframe on the paper (manual).
- [x] Discuss the design with @ekkyvalent.
- [x] Explain the Wireframe to the team.
- [x] Get an approval from the team. 
- [x] After sketching done, create/ put the wireframe' sketches to Inkscape/other drawing tools (digital).
## Deliverables

The design assets of the wireframe in SVG and PNG.
## Assumptions

The final work will be uploaded for everyone to see. This task will be finished by the end of this week.

**Comment by rutheodora** [comment]
guyss @ekkyvalent  @mhaidarh  @muhpatr  
tolong cek wireframe manual di whatsap, begitu setuju gw langsung ke inkscape

**Comment by mhaidarhanif** [comment]
Ntar @ekkyvalent bisa bantu untuk rapiin aset.

Ohya @rutheodora bisa bikin dulu design assets-nya, terus commit tapi sebaiknya di branch berbeda (misalnya branch `wireframe`). Jadi @ekkyvalent @rutheodora bisa diskusiin dan rapiin dulu aset-nya sebelum masuk `master`.
