### ISSUE TITLE
Test frontend app with selected test suite

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#60]
- Kind: Statement of Work
- Title: Test frontend app with selected test suite
- Author: Ekky Pramana
- Affiliation: Michi
- Date: 2016-04-22
- Version: 0.1
# SOW
## Overview

The frontend app that is now using Vue.js needs to be unit/functionally tested with selected test suite. Presumably JSHint, Mocha, and Chai.
## Tasks
- [ ] Properly look up for test scripts intended for unit/functional testing.
- [x] Try to automate the tests even more with CI/CD.
- [ ] Create more tests along with added functionalities.
## Deliverables

The test scripts can be run with `npm test`. The report (can be in various format) is then generated each time it's run. If tried and possible, automate this with CI/CD (refer to https://github.com/gunadarma-academy/asde-michi/issues/48).
## Dependencies

Progressed along with Streamline testing suite for backend and frontend (https://github.com/gunadarma-academy/asde-michi/issues/48) and Implement frontend based on the new designated routes, API, and data (https://github.com/gunadarma-academy/asde-michi/issues/55).
## References

Should work and passes all tests in order to make it a quality project.
- http://vuejs.org
- http://jshint.com
- http://mochajs.org
- http://chaijs.com
- http://jasmine.github.io
- https://karma-runner.github.io
