### ISSUE TITLE
Create logo for Arlin

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#7]
- Kind: Statement of Work
- Title: Create a branding style and logo design
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-03-18
- Version: 0.5
# SOW
## Overview

Create a branding style and logo design for Arlin's identity and website. I will use Inkscape and Photoshop (if needed) to make it.
## Tasks
- [x] Define the logo style (symbol, text, etc).
- [x] Create some logo variants.
- [x] Get an approval from the team members.
- [x] Store all of the design assets inside `design/brand` folder.
- [x] Upload the final design to the main repository.
## Deliverables

The branding syle, logo, and website wireframe will be uploaded to the main repo, anyone can see them `design` folder.
## Dependencies

My task, creating website wireframe, https://github.com/gunadarma-academy/asde-michi/issues/6 first.
## Assumptions

It will be done next week <when the ETA in date (21/22 March)>.

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi 
Regarding this, it's recommended for us to read any of these short ebooks:
UXPin e-Books https://studio.uxpin.com/ebooks

**Comment by mhaidarhanif** [comment]
@rutheodora I've slightly updated the overview to meet our needs.

**Comment by rutheodora** [comment]
okey, thanks for the reference, i've already download "Web UI Design Patterns 2016" e-book, will read it later.

**Comment by mhaidarhanif** [comment]
@rutheodora I just updated your Deliverables and Assumptions

**Comment by mhaidarhanif** [comment]
Useful references:
- https://medium.com/search?q=designing%20logo
- https://medium.com/@whycaniuse/logo-specification-the-modern-process-b285a9cfaa9e
- https://medium.com/art-marketing/a-designers-guide-to-creating-logo-files-ab91f05c72c4
- http://blog.hubspot.com/marketing/creating-logos-design-process
- http://www.thedesigncubicle.com/2009/05/11-steps-of-a-successful-logo-design-process

**Comment by rutheodora** [comment]
hasil rancangan logo (akan divoting nanti)

![g4469](https://cloud.githubusercontent.com/assets/17141470/13975400/88913d20-f0e7-11e5-833a-73e9ce5f9451.png)

**Comment by rutheodora** [comment]
Pallete webnya:
![pallete buat webnya](https://cloud.githubusercontent.com/assets/17141470/13975999/00c6b422-f0ee-11e5-96bb-9eb5d4aef22e.png)

hex color:
1. 96ca2dff
2. b5e655ff
3. edf7f2ff
4. 4bb5c1ff
5. 7fc6bcff

@ekkyvalent

**Comment by rutheodora** [comment]
@ekkyvalent @muhpatr @mhaidarh: berdasarkan vote, ini logo yang terpilih yaa, udah gw pull request ke repo kita juga.
![g5532](https://cloud.githubusercontent.com/assets/17141470/13980851/5d8aa090-f113-11e5-8f0b-5a42163d5a7d.png)

sengaja gw kasi bg item biar keliatannn.

**Comment by mhaidarhanif** [comment]
@rutheodora: Check out this very short logo page https://getgrav.org/media
