### ISSUE TITLE
Patria's Node.js CRUD and MongoDB learning

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#8]
- Kind: Statement of Work
- Title: Patria's Node.js CRUD and MongoDB learning
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-03-19
- Version: 0.2
# SOW
## Overview

After learning the basic of Node.js (#5), I'll starting to learn about how to create CRUD (Create, Read, Update, Delete) data function to database (MongoDB) in Node.JS.
## Tasks
- [x] learn about how to install and create database in MongoDB
- [x] learn about angular.js as the front-end framework
- [x] practice the MEAN Stack RESTful API tutorial
- [x] create contact list app as the implementation of CRUD
## Deliverables

This task will be finished by the end of this week.
## Dependencies

I have to know about node.js basic first (#5).
## Assumptions

The final work (contact list app) will be uploaded to my personal github page by the name: [contact-list-app](https://github.com/muhpatr/node-contact-app)

**Comment by muhpatr** [comment]
I'm starting to create this mini project by following the tutorial on this youtube video:
1. [Part 1](https://www.youtube.com/watch?v=kHV7gOHvNdk)
2. [Part 2](https://www.youtube.com/watch?v=7F1nLajs4Eo)
3. [Part 3](https://www.youtube.com/watch?v=oVIeMfvgTz8)
4. [Part 4](https://www.youtube.com/watch?v=iFsYJG3fGro)
5. [Part 5](https://www.youtube.com/watch?v=06_SIzYXgqQ)
