### ISSUE TITLE
Explain the basic features of Arlin v1

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#9]
- Kind: Product Definition
- Title: Explain the basic features of Arlin v1
- Author: M Haidar Hanif
- Affiliation: Michi
- Date: 2016-03-19
- Version: 0.1
# Product Definition
## Overview

Define the basic features in the Minimum Viable Product (MVP) of Arlin v1.
## Tasks
- [x] Define in details what's the most important features of Arlin in Product Documentation.
- [x] Explain about initial username setting for a new visitor.
- [x] Explain about posting a question as a user.
- [x] Explain about answering a question as a user.
## Deliverables

The specified document can explain the most important features of Arlin.
## Dependencies

Implement the initial data structures (https://github.com/gunadarma-academy/asde-michi/issues/10) before.
## Assumptions

These are the most important features of the application. We can say that we should learn from Haaash and StackOverflow.

**Comment by mhaidarhanif** [comment]
Let's see this as a reference:
![haaash1](https://cloud.githubusercontent.com/assets/235584/13898306/7bb45578-edff-11e5-8ba6-2b4b9120629e.png)

[This is from http://michi.haaash.com, this new/beta version is kind of different from the previous version of Haaash.]

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi
To see and experience an actual stable working app of Haaash (not a demo), please visit http://5oopx.haaash.com
